######################## default configuration ####################
baseURL = "https://www.continuoustestingmeetup.com/"
title = "Continuous Testing Meetup"
theme = "twenty-twenty-hugo"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here
# google analytics
googleAnalytics = "" # example : UA-123-45



############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"

############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
name = "About"
URL = "about"
weight = 2

[[menu.main]]
name = "Events"
URL = "events"
weight = 3

[[menu.main]]
name = "Submit your talk"
URL = "submit"
weight = 4

# only desktop menu
[[menu.desktop]]
name = "About"
URL = "about"
weight = 1

# only desktop menu
[[menu.desktop]]
name = "Submit your talk"
URL = "submit"
weight = 2


#################### default parameters ################################
[params]
# Meta data
description = "A community for testers & developers"
author = "Continuous Testing Meetup"


# banner
[params.banner]
heading = ""
image = "images/ctm_online.png"

# events
[params.events]
heading = "A community for testers & developers"

# call to action
[params.call_to_action]
enable = false
title = "Contact us for more information."
content = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
button_label = "Contact Us"
button_url = "contact"

# gallery
[params.gallery]
enable = false

  [[params.gallery.gallery_item ]]
  image = "images/ctm_online.png"
  
  [[params.gallery.gallery_item ]]
  image = "images/ctm_online.png"


# footer
[params.footer]
title = "Continuous Testing Meetup"
content = "CTM is a community for testers and developers to share their ideas and learn from peers. <br><br> We bring people together to discuss not only technology but also all the required skills to succeed in today's testing industry."
twitter_url = "https://twitter.com/ct_meetup"
twitter_description = "ct_meetup"
twitter_icon = "fa fa-twitter"
meetup_barcelona_url = "https://www.meetup.com/continuous-testing-meetup-barcelona"
meetup_barcelona_description = "Barcelona"
meetup_barcelona_icon = "fa fa-meetup"
meetup_berlin_url = "https://www.meetup.com/continuous-testing-meetup-berlin"
meetup_berlin_description = "Berlin"
meetup_berlin_icon = "fa fa-meetup"
meetup_london_url = "https://www.meetup.com/continuous-testing-meetup-london"
meetup_london_description = "London"
meetup_london_icon = "fa fa-meetup"
meetup_san_francisco_url = "https://www.meetup.com/continuous-testing-meetup-san-francisco/"
meetup_san_francisco_description = "San Francisco"
meetup_san_francisco_icon = "fa fa-meetup"
github_url = "https://github.com/continuoustestingmeetup/continuoustestingmeetup.github.io"
github_description = "GitHub"
github_icon = "fa fa-github"
slack_url = "https://join.slack.com/t/ctm-online/shared_invite/zt-eo35byb8-taqP3PsXq~Hb49NtIunaOw"
slack_description = "CTM Slack Workspace"
slack_icon = "fa fa-slack"
copyright = "&copy; 2024 Continuous Testing Meetup"
