[build]
publish = "public"
command = "TZ=Europe/Berlin hugo --minify --buildFuture"

[context.production.environment]
HUGO_VERSION = "0.110.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "TZ=Europe/Berlin hugo --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.110.0"

[context.branch-deploy]
command = "TZ=Europe/Berlin hugo --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.110.0"