backend:
  name: github
  branch: dev
  repo: continuoustestingmeetup/continuoustestingmeetup.github.io/
  base_url: https://www.continuoustestingmeetup.com/
  auth_endpoint: auth
publish_mode: editorial_workflow
media_folder: "static/images"
public_folder: "/images"
collections: # A list of collections the CMS should be able to edit
  - name: "events" # Used in routes, e.g., /admin/collections/events
    label: "Event" # Used in the UI
    folder: "content/events" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}" # Filename template, e.g., YYYY-MM-DD.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Images", name: "images", widget: "list"}
      - {label: "Categories", name: "categories", widget: "list", default: ["ctm - Online"]}
      - {label: "Tags", name: "tags", widget: "list", default: ["ctm", "online"]}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Images Path", name: "path", widget: "string"}
      - {label: "Registration Link", name: "registration", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}