name: Publish CTM Site

on:
  push:
    branches:
      - dev
  schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    - cron: '30 1 * * *'
    
jobs:
  deploy:
    # Skip job based on the commit message
    if: contains(toJson(github.event.commits), '[skip ci]') == false
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
      - name: Update theme
        run: git submodule update --init --recursive
      - name: Build
        run: TZ=Europe/Berlin hugo --minify --buildFuture
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./public
          publish_branch: publish
          user_name: 'diemol-bot'
          user_email: 'diemol-bot@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
          cname: www.continuoustestingmeetup.com
